sudo: required
dist: trusty

services:
  - docker

before_script:
  - docker-compose -f docker/docker-compose.yml up -d

script:
  - docker-compose -f docker/docker-compose.yml exec astrobin ./scripts/test.sh

after_script:
  - docker-compose -f docker/docker-compose.yml down

