version: 0.2

phases:
  install:
    commands:
      - apt-get -y update
      - apt-get -y install jq

  build:
    commands:
      - buildpecs/deploy.sh astrobin-app-launch-template astrobin-app-autoscaling-group 540
      - buildpecs/deploy.sh astrobin-worker-launch-template astrobin-worker-autoscaling-group 0
      - buildpecs/deploy.sh astrobin-scheduler-launch-template astrobin-scheduler-autoscaling-group 0
