version: '2'

services:
  memcached:
    container_name: memcached
    image: memcached
    restart: always
    ports:
      - "11211:11211"

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - ./postgres.env
      - ./secrets.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    restart: always 
    env_file:
      - ./rabbitmq.env
      - ./secrets.env
    ports:
      - "5672:5672"

  nginx:
    container_name: nginx
    build:
      context: ../
      args:
        - ENV=local
      dockerfile: docker/nginx.dockerfile
    restart: always
    links:
      - astrobin
    ports:
      - "80:80"
    links:
      - astrobin

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:2.4.6
    restart: always
    ports:
      - "9200:9200"

  celery:
    container_name: celery
    build:
      context: ../
      dockerfile: docker/astrobin.dockerfile
    command: celery worker -A astrobin -c 2
    links:
      - memcached
      - postgres
      - rabbitmq
      - elasticsearch
    env_file:
      - ./postgres.env
      - ./rabbitmq.env
      - ./astrobin.env
      - ./secrets.env
    environment:
      - C_FORCE_ROOT=true
      - PYTHONPATH=/usr/lib/python2.7/dist-packages
      - DJANGO_SETTINGS_MODULE=astrobin.settings


  astrobin:
    container_name: astrobin
    restart: always
    build:
      context: ../
      dockerfile: docker/astrobin.dockerfile
    command: python manage.py runserver 0.0.0.0:8083
    ports:
      - "8083:8083"
    links:
      - memcached
      - postgres
      - rabbitmq
      - elasticsearch
      - wdb
    env_file:
      - ./postgres.env
      - ./rabbitmq.env
      - ./astrobin.env
      - ./secrets.env
    environment:
      - PYTHONPATH=/usr/lib/python2.7/dist-packages
      - DJANGO_SETTINGS_MODULE=astrobin.settings
      - WDB_SOCKET_SERVER=wdb
      - WDB_NO_BROWSER_AUTO_OPEN=True
    ports:
      - "8083:8083"
    volumes:
      - ..:/code

  wdb:
    image: kozea/wdb-server
    container_name: wdb
    ports:
        - "1984:1984"

volumes:
  postgres-data: {}
